- name: Catalogue 
  hosts: catalogue 
  become: yes 
  tasks:
  - name: Disabling Old NodeJS and Enabling NodeJS:20
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

  